Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [9]:
import numpy as np
n = 10
np.arange(n-1, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [23]:
n = 5
x = np.diag(np.arange(n, -1, -1))
print(x)
sum(x[i][i] for i in range(n))

[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]


15

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [25]:
a = np.array( [ [4, 2, 1], [1, 3, 0] , [0, 5, 4] ])
b = np.array([4, 12, -3])

from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

Задача 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем.
На сайт заходит очередной посетитель, о покупках которого известно следующее:

next_user_stats = np.array([0, 1, 2, 0, 0, 0])
Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [35]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine( a, b ):
        
    aLength = np.sqrt( (a*a).sum() )
    bLength = np.sqrt( (b*b).sum() )

    return np.dot( a, b ) / ( aLength * bLength )


best_match = max(cosine( next_user_stats, user) for user in users_stats)

i = 1
for user in users_stats:
    if cosine( next_user_stats, user) == best_match:
        print('Похожий пользователь ID', i)
    else:
        i += 1
    

Похожий пользователь ID 8
